### ISSUE TITLE
Issue with infinite scroll

### ISSUE THREAD

**Issue by mczachurski** [VernissageApp/VernissageWeb#97]
At times, the infinite scroll feature does not work, and in order to load the next set of images, we have to navigate to a different page and then return to the gallery.

**Comment by mgrzeca** [comment]
It seems there was a misunderstanding in the description of the issue. The problem is actually the opposite. Navigating to a different view and then returning to the timeline is what breaks the infinite scroll. To fix it, you need to reload the page (e.g., Cmd-R in Safari), not navigate away and come back :)
